[package]
name = "fluence-fork-libp2p-identify"
edition = "2018"
description = "Nodes identifcation protocol for libp2p"
version = "0.28.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[lib]
name = "libp2p_identify"

[dependencies]
futures = "0.3.1"
libp2p-core = { version = "0.27.1", path = "../../core", package = "fluence-fork-libp2p-core" }
libp2p-swarm = { version = "0.28.0", path = "../../swarm", package = "fluence-fork-libp2p-swarm" }
log = "0.4.1"
prost = "0.7"
smallvec = "1.0"
wasm-timer = "0.2"

[dev-dependencies]
async-std = "1.6.2"
libp2p-mplex = { path = "../../muxers/mplex", package = "fluence-fork-libp2p-mplex" }
libp2p-noise = { path = "../../transports/noise", package = "fluence-fork-libp2p-noise" }
libp2p-tcp = { path = "../../transports/tcp", package = "fluence-fork-libp2p-tcp" }

[build-dependencies]
prost-build = "0.7"

[package.metadata.workspaces]
independent = true
