[package]
name = "fluence-fork-libp2p-identify"
edition = "2018"
description = "Nodes identifcation protocol for libp2p"
version = "0.20.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.3.1"
libp2p-core = { version = "0.20.0", path = "../../core", package = "fluence-fork-libp2p-core" }
libp2p-swarm = { version = "0.20.0", path = "../../swarm", package = "fluence-fork-libp2p-swarm" }
log = "0.4.1"
prost = "0.6.1"
smallvec = "1.0"
wasm-timer = "0.2"

[dev-dependencies]
async-std = "1.6.2"
libp2p-mplex = { path = "../../muxers/mplex", package = "fluence-fork-libp2p-mplex" }
libp2p-secio = { path = "../../protocols/secio", package = "fluence-fork-libp2p-secio" }
libp2p-tcp = { path = "../../transports/tcp", features = ["async-std"], package = "fluence-fork-libp2p-tcp" }

[build-dependencies]
prost-build = "0.6"


[package.metadata.workspaces]
independent = true
