[package]
name = "fluence-fork-libp2p-yamux"
edition = "2018"
description = "Yamux multiplexing protocol for libp2p"
version = "0.30.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[lib]
name = "libp2p_yamux"

[dependencies]
futures = "0.3.1"
libp2p-core = { version = "0.27.2", path = "../../core", package = "fluence-fork-libp2p-core" }
parking_lot = "0.11"
thiserror = "1.0"
yamux = "0.8.1"

[package.metadata.workspaces]
independent = true
