[package]
name = "fluence-fork-multistream-select"
description = "Multistream-select negotiation protocol for libp2p"
version = "0.9.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[lib]
name = "multistream_select"

[dependencies]
bytes = "0.5"
futures = "0.3"
log = "0.4"
pin-project = "1.0.0"
smallvec = "1.0"
unsigned-varint = "0.5"

[dev-dependencies]
async-std = "1.6.2"
env_logger = "0.8"
libp2p-core = { path = "../../core", package = "fluence-fork-libp2p-core" }
libp2p-mplex = { path = "../../muxers/mplex", package = "fluence-fork-libp2p-mplex" }
libp2p-plaintext = { path = "../../protocols/plaintext", package = "fluence-fork-libp2p-plaintext" }
quickcheck = "0.9.0"
rand = "0.7.2"
rw-stream-sink = "0.2.1"

[package.metadata.workspaces]
independent = true
