[package]
name = "fluence-fork-libp2p-dns"
edition = "2018"
description = "DNS transport implementation for libp2p"
version = "0.27.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[lib]
name = "libp2p_dns"

[dependencies]
libp2p-core = { version = "0.27.1", path = "../../core", package = "fluence-fork-libp2p-core" }
log = "0.4.1"
futures = "0.3.1"

[package.metadata.workspaces]
independent = true
