[package]
name = "fluence-fork-libp2p-core-derive"
edition = "2018"
description = "Procedural macros of libp2p-core"
version = "0.21.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[lib]
name = "libp2p_core_derive"
proc-macro = true

[dependencies]
syn = { version = "1.0.8", default-features = false, features = ["clone-impls", "derive", "parsing", "printing", "proc-macro"] }
quote = "1.0"

[dev-dependencies]
libp2p = { path = "../..", package = "fluence-fork-libp2p" }

[package.metadata.workspaces]
independent = true
