[package]
name = "fluence-fork-libp2p-request-response"
edition = "2018"
description = "Generic Request/Response Protocols"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-trait = "0.1"
futures = "0.3.1"
libp2p-core = { version = "0.20.0", path = "../../core", package = "fluence-fork-libp2p-core" }
libp2p-swarm = { version = "0.20.0", path = "../../swarm", package = "fluence-fork-libp2p-swarm" }
smallvec = "1.4"
wasm-timer = "0.2"

[dev-dependencies]
async-std = "1.6.2"
libp2p-noise = { path = "../noise", package = "fluence-fork-libp2p-noise" }
libp2p-tcp = { path = "../../transports/tcp", features = ["async-std"], package = "fluence-fork-libp2p-tcp" }
libp2p-yamux = { path = "../../muxers/yamux", package = "fluence-fork-libp2p-yamux" }
rand = "0.7"

[package.metadata.workspaces]
independent = true
