[package]
name = "fluence-fork-libp2p-deflate"
edition = "2018"
description = "Deflate encryption protocol for libp2p"
version = "0.27.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[lib]
name = "libp2p_deflate"

[dependencies]
futures = "0.3.1"
libp2p-core = { version = "0.27.2", path = "../../core", package = "fluence-fork-libp2p-core" }
flate2 = "1.0"

[dev-dependencies]
async-std = "1.6.2"
libp2p-tcp = { path = "../../transports/tcp", package = "fluence-fork-libp2p-tcp" }
quickcheck = "0.9"
rand = "0.7"

[package.metadata.workspaces]
independent = true
